---
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
        name: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        name: check-shebang-scripts-are-executable
      - id: check-symlinks
        name: check-symlinks
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: no-commit-to-branch
        name: prevent-commits-to-default-branch
      - id: check-merge-conflict
        name: check-merge-conflict

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
        alias: editorconfig
        name: editorconfig

  - repo: https://github.com/bridgecrewio/checkov
    rev: 2.0.671
    hooks:
      - id: checkov
        name: checkov
        args: ["--config-file", ".checkov.yml"]

  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform-fmt
        language: script
        types: [terraform]
        entry: scripts/run_system_linter.py terraform fmt --run-system-linter-files
      - id: terragrunt-hclfmt
        name: terragrunt-hclfmt
        alias: terragrunt-fmt
        language: script
        files: "(^|/)terragrunt.hcl$"
        entry: scripts/run_system_linter.py terragrunt hclfmt
      - id: tf-docs-modules
        name: tf-docs-modules
        language: script
        files: "^terraform/modules/.*/*.tf"
        require_serial: true
        entry: scripts/generate_tf_docs.sh
      - id: tf-docs-examples
        name: tf-docs-examples
        language: script
        files: "^terraform/examples/.*/*.tf"
        require_serial: true
        entry: scripts/generate_tf_docs.sh
      - id: hadolint
        name: hadolint
        language: script
        types: [dockerfile]
        entry: scripts/run_system_linter.py hadolint
      - id: shellcheck
        name: shellcheck
        language: script
        types: [shell]
        entry: scripts/run_system_linter.py shellcheck
      - id: actionlint
        name: actionlint
        language: script
        types: [yaml]
        files: "^.github/workflows/"
        # The two -ignore flags below are because outputs seem to be not recognized yet on called workflows.
        # When https://github.com/rhysd/actionlint/issues/91 is resolved it should be ok to remove these.
        entry: >
          scripts/run_system_linter.py actionlint
          -ignore 'property "(image|tag|image-tag|github_token)" is not defined in object type'
          -ignore 'unexpected key "outputs" for "workflow_call" section'

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: bandit

  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.7
    hooks:
      - id: pylint
        name: pylint

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: flake8

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        name: prettier

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        name: yamllint
        args: ["--strict"]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.4.0
    hooks:
      - id: markdownlint-cli2
        alias: markdownlint
        name: markdownlint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        name: codespell

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.14.3
    hooks:
      - id: check-github-workflows
        name: check-github-workflows
      - id: check-renovate
        name: check-renovate
        types: [file]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        name: detect-secrets
        args: [--exclude-secrets, mock]
