---
name: "Inputs No Inputs"

on:
  workflow_dispatch:
    inputs:
      my-flag:
        description: "My flag"
        type: boolean
        default: false
        required: false
  push:
    branches:
      - inputs-no-inputs

defaults:
  run:
    shell: bash

jobs:
  example:
    runs-on: ubuntu-22.04
    name: "Example"
    steps:
      - id: resolve-flag
        uses: actions/github-script@v6
        with:
          script: |
            if ("${{inputs.my-flag}}" === "") {
              return false;
            }
            return ${{inputs.my-flag}};
          result-encoding: json
      - run: |
          echo "output: ${{ steps.resolve-flag.outputs.result }}"
          echo "env: ${{ env.my-flag }}"
          echo "my flag: ${{ inputs.my-flag }}"
