---
name: "Inputs No Inputs"

on:
  workflow_dispatch:
    inputs:
      my-flag:
        description: "My flag"
        type: boolean
        default: false
        required: false
  push:
    branches:
      - inputs-no-inputs

defaults:
  run:
    shell: bash

jobs:
  example:
    runs-on: ubuntu-20.04
    name: "Example"
    steps:
      - name: "Resolve my-flag"
        id: resolve-flag
        run: |
          if [[ -z ${{inputs.my-flag}} ]]; then
            echo "my-flag=false" >> "$GITHUB_OUTPUT"
          else
            echo "my-flag=${{inputs.my-flag}}" >> "$GITHUB_OUTPUT"
          fi
      - run: |
          echo "output: ${{ steps.resolve-flag.outputs.my-flag }}"
          echo "env: ${{ env.my-flag }}"
          echo "my flag: ${{ inputs.my-flag }}"
