---
name: "Needs Loop"

on:
  workflow_dispatch:
  push:
    branches: main

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  success:
    runs-on: ubuntu-20.04
    steps:
      - run: exit 0
  failure:
    runs-on: ubuntu-20.04
    steps:
      - run: exit 1
  skipped:
    runs-on: ubuntu-20.04
    if: false
    steps:
      - uses: actions/checkout@v4
  loop:
    runs-on: ubuntu-20.04
    if: always()
    needs:
      - success
      - failure
      - skipped
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            results = [
              ${{ needs.success.result }},
              ${{ needs.failure.result }},
              ${{ needs.skipped.result }}
            ]
            for (let result of results) {
              console.log(result);
            }
