---
name: "Needs Loop"

on:
  workflow_dispatch:
  push:
    branches: main

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  a:
    runs-on: ubuntu-22.04
    steps:
      - run: exit 0
  b:
    runs-on: ubuntu-22.04
    steps:
      - run: exit 1
  c:
    runs-on: ubuntu-22.04
    if: false
    steps:
      - uses: actions/checkout@v4
  d:
    runs-on: ubuntu-22.04
    if: always()
    needs:
      - a
      - b
      - c
    steps:
      - run: |
          results=( \
            ${{ needs.a.result }} \
            ${{ needs.b.result }} \
            ${{ needs.c.result }} \
          )
          for i in "${!results[@]}"; do
              echo "${results[$i]}"
          done
