---
name: "PR Script"

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  prscript:
    name: Script
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          # get the whole repo, not just the last commit, so
          # we can compare changes on this branch to main
          fetch-depth: 0
      - name: Script
        run: |
          # useful if this job runs in a container
          # git config --global --add safe.directory "$GITHUB_WORKSPACE"
          
          echo "status:"
          git status
          echo "branches:"
          git branch -la

          echo "head:"
          git rev-parse --verify HEAD
          echo "main:"
          git rev-parse --verify origin/main~1
