---
name: "PR Script"

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build-matrices:
    name: Build Matrices
    runs-on: ubuntu-22.04
    outputs:
      matrix-silver-200: ${{ steps.build-silver-200-matrix.outputs.matrix }}
      matrix-silver-300: ${{ steps.build-silver-300-matrix.outputs.matrix }}
      matrix-silver-400: ${{ steps.build-silver-400-matrix.outputs.matrix }}
      matrix-silver-500: ${{ steps.build-silver-500-matrix.outputs.matrix }}
      matrix-silver-510: ${{ steps.build-silver-510-matrix.outputs.matrix }}
      # matrix-gold-200: ${{ steps.build-gold-200-matrix.outputs.matrix }}
      # matrix-gold-300: ${{ steps.build-gold-300-matrix.outputs.matrix }}
      # matrix-gold-400: ${{ steps.build-gold-400-matrix.outputs.matrix }}
      # matrix-gold-500: ${{ steps.build-gold-500-matrix.outputs.matrix }}
      # matrix-gold-510: ${{ steps.build-gold-510-matrix.outputs.matrix }}
      count-silver-migration: ${{ steps.build-silver-migration.outputs.count }}
      count-silver-100: ${{ steps.build-silver-100.outputs.count }}
      count-silver-200: ${{ steps.build-silver-200-matrix.outputs.count }}
      count-silver-300: ${{ steps.build-silver-300-matrix.outputs.count }}
      count-silver-400: ${{ steps.build-silver-400-matrix.outputs.count }}
      count-silver-500: ${{ steps.build-silver-500-matrix.outputs.count }}
      count-silver-510: ${{ steps.build-silver-510-matrix.outputs.count }}
      # count-gold-200: ${{ steps.build-gold-200-matrix.outputs.count }}
      # count-gold-300: ${{ steps.build-gold-300-matrix.outputs.count }}
      # count-gold-400: ${{ steps.build-gold-400-matrix.outputs.count }}
      # count-gold-500: ${{ steps.build-gold-500-matrix.outputs.count }}
      # count-gold-510: ${{ steps.build-gold-510-matrix.outputs.count }}
      count: ${{ steps.count.outputs.count }}
    steps:
      - uses: actions/checkout@v4
        with:
          # get the whole repo, not just the last commit, so
          # we can compare changes on this branch to main
          fetch-depth: 0
      - name: "Build Silver Migration"
        id: build-silver-migration
        run: |
          COUNT=0
          git diff HEAD origin/main --name-only
          for filename in $(git diff HEAD origin/main --name-only)
          do
            dir="$(dirname $filename)"
            if [[ "terraform/roots/silver/migrations" == "$dir" ]]; then
              COUNT=1
            fi
          done
          echo "Silver 100 count: $COUNT"
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
      - name: "Build Silver 100"
        id: build-silver-100
        run: |
          COUNT=0
          git diff HEAD origin/main --name-only
          for filename in $(git diff HEAD origin/main --name-only)
          do
            dir="$(dirname $filename)"
            if [[ "terraform/roots/silver/100-pre-bootstrap" == "$dir" ]]; then
              COUNT=1
            fi
          done
          echo "Silver 100 count: $COUNT"
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
      - name: "Build Silver 200 Matrix"
        id: build-silver-200-matrix
        run: |
          MATRIX="$(cat matrix1.json)"
          echo "$MATRIX" | jq
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
          COUNT=$(echo "$MATRIX" | jq '.include | length')
          echo "Silver 200 count: $COUNT"
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
      - name: "Build Silver 300 Matrix"
        id: build-silver-300-matrix
        run: |
          MATRIX="$(cat matrix1.json)"
          echo "$MATRIX" | jq
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
          COUNT=$(echo "$MATRIX" | jq '.include | length')
          echo "Silver 300 count: $COUNT"
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
      - name: "Build Silver 400 Matrix"
        id: build-silver-400-matrix
        run: |
          MATRIX="$(cat matrix1.json)"
          echo "$MATRIX" | jq
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
          COUNT=$(echo "$MATRIX" | jq '.include | length')
          echo "Silver 400 count: $COUNT"
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
      - name: "Build Silver 500 Matrix"
        id: build-silver-500-matrix
        run: |
          MATRIX="$(cat matrix1.json)"
          echo "$MATRIX" | jq
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
          COUNT=$(echo "$MATRIX" | jq '.include | length')
          echo "Silver 500 count: $COUNT"
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
      - name: "Build Silver 510 Matrix"
        id: build-silver-510-matrix
        run: |
          MATRIX="$(cat matrix1.json)"
          echo "$MATRIX" | jq
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
          COUNT=$(echo "$MATRIX" | jq '.include | length')
          echo "Silver 510 count: $COUNT"
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
      - name: "Count all plans"
        id: count
        run: |
          COUNT="$((${{ steps.build-silver-100.outputs.count }} + \
            ${{ steps.build-silver-200-matrix.outputs.count }} + \
            ${{ steps.build-silver-300-matrix.outputs.count }} + \
            ${{ steps.build-silver-400-matrix.outputs.count }} + \
            ${{ steps.build-silver-500-matrix.outputs.count }} + \
            ${{ steps.build-silver-510-matrix.outputs.count }}))"
          echo "All expected plans (100 through 510): $COUNT"
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
      # - name: Build Matrices
      #   run: |
      #     # useful if this job runs in a container
      #     # git config --global --add safe.directory "$GITHUB_WORKSPACE"

      #     echo "status:"
      #     git status
      #     echo "branches:"
      #     git branch -la

      #     echo "head:"
      #     git rev-parse --verify HEAD
      #     echo "main:"
      #     git rev-parse --verify origin/main~1

  post-plans:
    name: Post Plan Results
    runs-on: ubuntu-22.04
    needs:
      - build-matrices
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download plan results
        uses: actions/download-artifact@v3
        with:
          path: plans
      - name: Count expected plans
        id: count-expected-plans
        env:
          matrix200: ${{ needs.build-matrices.outputs.matrix-silver-200 }}
          matrix300: ${{ needs.build-matrices.outputs.matrix-silver-300 }}
          matrix400: ${{ needs.build-matrices.outputs.matrix-silver-400 }}
          matrix500: ${{ needs.build-matrices.outputs.matrix-silver-500 }}
          matrix510: ${{ needs.build-matrices.outputs.matrix-silver-510 }}
        run: |
          count200="$(echo $matrix200 | jq '.include | length')"
          count300="$(echo $matrix300 | jq '.include | length')"
          count400="$(echo $matrix400 | jq '.include | length')"
          count500="$(echo $matrix500 | jq '.include | length')"
          count510="$(echo $matrix510 | jq '.include | length')"
          count="($count200 + $count300 + $count400 + $count500 + $count510)"
          echo "count=$count"
          echo "count=$count" >> "$GITHUB_OUTPUT"
