---
name: Terraform Module Changelog Comparison

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      compare_from:
        type: string
        description: a git reference to compare from for determining changelog changes
        default: main
      compare_to:
        type: string
        description: a git reference to compare to for determining changelog changes
        default: HEAD
      dry_run:
        type: boolean
        default: true

jobs:
  diff:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Checkout From
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.compare_from }}
      - name: List "From" Versions
        id: versions_from
        run: echo "versions=$(python3 scripts/print_all_module_versions.py)" >> $GITHUB_OUTPUT
      - name: Checkout To
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.compare_to }}
      - name: List "To" Versions
        id: versions_to
        run: echo "versions=$(python3 scripts/print_all_module_versions.py)" >> $GITHUB_OUTPUT
      - name: Compare Version Lists
        run: |
          echo "Module Versions at ${{ inputs.compare_from }}:"
          echo "${{ steps.versions_from.outputs.versions }}"
          echo "Module Versions at ${{ inputs.compare_to }}:"
          echo "${{ steps.versions_to.outputs.versions }}"
          echo "New versions detected:"
          echo '{"before": ${{ steps.versions_from.outputs.versions }}, "after": ${{ steps.versions_to.outputs.versions }}}' | jq '.after - .before'
