---
name: Terraform Module Changelog Comparison

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      compare_from:
        description: a git reference to compare from for determining changelog changes
        type: string
        default: main
      compare_to:
        description: a git reference to compare to for determining changelog changes
        type: string
        default: HEAD
      release_module_versions:
        type: boolean
        default: false
    secrets:
      PAT_WORKFLOW_WRITE:
        description: a PAT with contents:write and workflows:write
        required: true

jobs:
  diff:
    runs-on: ubuntu-22.04
    outputs:
      count: ${{ steps.compare.outputs.count }}
      diff: ${{ steps.compare.outputs.diff }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v4
        with:
          # so we can checkout any reference or relative
          fetch-depth: 0
      - name: Compare Module Versions
        id: compare
        run: |
          set -ex
          git checkout ${{ inputs.compare_from }}
          VERSIONS_FROM="$(python3 scripts/print_all_module_versions.py)"
          git checkout ${{ inputs.compare_to }}
          VERSIONS_TO="$(python3 scripts/print_all_module_versions.py)"

          echo "Module Versions at ${{ inputs.compare_from }}:"
          echo "$VERSIONS_FROM"
          echo "Module Versions at ${{ inputs.compare_to }}:"
          echo "$VERSIONS_TO"
          echo "New versions detected:" >> "$GITHUB_STEP_SUMMARY"
          DIFF=$(echo "{\"before\": $VERSIONS_FROM, \"after\": $VERSIONS_TO}" | jq -c '.after - .before')
          echo "$DIFF" >> "$GITHUB_STEP_SUMMARY"
          echo diff="$DIFF" >> "$GITHUB_OUTPUT"
          echo count="$(echo "$DIFF" | jq 'length')" >> "$GITHUB_OUTPUT"
  tag_and_release:
    runs-on: ubuntu-22.04
    if: needs.diff.outputs.count > 0
    needs: [diff]
    strategy:
      fail-fast: false
      max-parallel: 256
      matrix:
        tag: ${{ fromJson(needs.diff.outputs.diff) }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.compare_to }}
          token: ${{ secrets.PAT_WORKFLOW_WRITE }}
      - name: Preview Release Contents
        id: fetch_release_contents
        run: |
          CONTENTS=$(python3 scripts/print_version_changelog.py ${{ matrix.tag }})
          {
            echo "contents<<EOF" ;
            echo "$CONTENTS" ;
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          {
            echo "The release notes for ${{ matrix.tag }} will be:" ;
            echo "$CONTENTS" ;
          } >> "$GITHUB_STEP_SUMMARY"
      - if: ${{ inputs.release_module_versions }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag "${{ matrix.tag }}"
          git push --tags
      - name: Create Release
        if: ${{ inputs.release_module_versions }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ matrix.tag }}
          body: ${{ steps.fetch_release_contents.outputs.contents }}
