---
name: "Terraform Module Release"

on:
  workflow_dispatch:
    inputs:
      compare_from:
        description: a git reference to compare from for determining changelog changes
        type: string
        default: main
      compare_to:
        description: a git reference to compare to for determining changelog changes
        type: string
        default: changelog-detection
      release_module_versions:
        description: whether to tag and release the module version(s)
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  example:
    name: "Example"
    uses: ./.github/workflows/reusable-terraform-module-changelog.yml
    permissions:
      contents: read
    with:
      compare_from: ${{ inputs.compare_from }}
      compare_to: ${{ inputs.compare_to }}
      release_module_versions: ${{ inputs.release_module_versions }}
    secrets: inherit # pragma: allowlist secret
