---
name: "Terraform Module PR"

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  example:
    name: "Example"
    uses: ./.github/workflows/reusable-terraform-module-changelog.yml
    permissions:
      contents: read
    with:
      compare_from: main^
      compare_to: main
      release_module_versions: true
    secrets: inherit # pragma: allowlist secret
