---
name: "Terraform Module Release"

on:
  workflow_dispatch:
    inputs:
      compare_from:
        description: a git ref to compare _from_ for determining module versions
        type: string
        default: 4e9255afee288cf689c09026234bb624ab993bd3 # pragma: allowlist secret
      compare_to:
        description: a git ref to compare _to_ for determining module versions
        type: string
        default: 432a0f95b4e490aced7656d48ae868e614834770 # pragma: allowlist secret
      release_module_versions:
        description: tag and release the module version(s)?
        type: boolean
        default: true

defaults:
  run:
    shell: bash

jobs:
  example:
    name: "Example"
    uses: ./.github/workflows/reusable-terraform-module-changelog.yml
    permissions:
      actions: write
      contents: write
    with:
      compare_from: ${{ inputs.compare_from }}
      compare_to: ${{ inputs.compare_to }}
      release_module_versions: ${{ inputs.release_module_versions }}
    secrets: inherit # pragma: allowlist secret
