---
name: "Terraform Module PR"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  example:
    name: "Example"
    uses: ./.github/workflows/reusable-terraform-module-changelog.yml
    permissions:
      contents: read
    with:
      compare_from: ${{ github.pull_request.base.ref }}
      compare_to: ${{ github.pull_request.head.ref }}
    secrets: inherit
