---
name: "Terraform Module Test"

on:
  workflow_dispatch:
    inputs:
      compare_from:
        type: string
        default: main
      compare_to:
        type: string
        default: changelog-detection

defaults:
  run:
    shell: bash

jobs:
  example:
    name: "Example"
    uses: ./.github/workflows/reusable-terraform-module-changelog.yml
    permissions:
      contents: read
    with:
      compare_from: ${{ inputs.compare_from }}
      compare_to: ${{ inputs.compare_to }}
      dry_run: true
      release_module_versions: true
    secrets: inherit # pragma: allowlist secret
